// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkSnL0mg6NDRz-FM0YVr_-3rFL9_XbnZA',
    appId: '1:377686682717:web:e0b472154c82fd300671b4',
    messagingSenderId: '377686682717',
    projectId: 'vidhyatri-ed316',
    authDomain: 'vidhyatri-ed316.firebaseapp.com',
    storageBucket: 'vidhyatri-ed316.appspot.com',
    measurementId: 'G-0QZMG53H12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYyVbNm-H4SbyU7P8yBNffZItrQpLsn4U',
    appId: '1:377686682717:android:40e98f67cb337d280671b4',
    messagingSenderId: '377686682717',
    projectId: 'vidhyatri-ed316',
    storageBucket: 'vidhyatri-ed316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ5IpsmgkTBjlzzhQSPbEaYaA92dHJkiM',
    appId: '1:377686682717:ios:29a4ced4ed7cf2a00671b4',
    messagingSenderId: '377686682717',
    projectId: 'vidhyatri-ed316',
    storageBucket: 'vidhyatri-ed316.appspot.com',
    iosBundleId: 'com.codexwr.vidhyatri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ5IpsmgkTBjlzzhQSPbEaYaA92dHJkiM',
    appId: '1:377686682717:ios:53a4a939a2f4ad880671b4',
    messagingSenderId: '377686682717',
    projectId: 'vidhyatri-ed316',
    storageBucket: 'vidhyatri-ed316.appspot.com',
    iosBundleId: 'com.codexwr.vidhyatri.RunnerTests',
  );
}
